### ISSUE TITLE
Name the service port

### ISSUE THREAD

**Issue by pessoa** [montblu/terraform-kubernetes-deployment#12]
This is needed to eg. reference the port in kind: ServiceMonitor

https://github.com/montblu/terraform-kubernetes-deployment/blob/master/main.tf#L641-L6461

**Comment by jdaMachado** [comment]
@pessoa  Could you show a brief example on how it would be referenced?

**Comment by pessoa** [comment]
Something like this:
![Screenshot_20240326_103348](https://github.com/montblu/terraform-kubernetes-deployment/assets/1252892/3c5260f1-81aa-440a-9043-f79d6bd546c1)

**Comment by MiguelNdeCarvalho** [comment]
Closed in #17
